Repository OmerFlame/SwiftRant, pull requests merged in 2022-10, with the labels that each got.

#12 Change `Notifications.Categories`'s enum type to `Int` in order to add support for converting the enum value to both a `String` and an `Int`
  Sources/SwiftRant/NotificationFeed.swift
  Sources/SwiftRant/SwiftRant.swift
  Sources/SwiftRant/VoteState.swift
  Tests/SwiftRantTests/SwiftRantTests.swift
Labels: enhancement

#17 SwiftRant public init
  Sources/SwiftRant/SwiftRant.swift
Labels: enhancement

#18 Adding missing ampersand (&) before the url parameter prev_set
  Sources/SwiftRant/SwiftRant.swift
Labels: bug

#19 Adding percent encoding for feed url
  Sources/SwiftRant/SwiftRant.swift
Labels: bug

#20 Adding a slash (/) before the notification category in the url of notifications feed
  Sources/SwiftRant/SwiftRant.swift
Labels: bug

#21 Added Sort and Range for the rant feed
  Sources/SwiftRant/RantFeed.swift
  Sources/SwiftRant/SwiftRant.swift
Labels: enhancement

#22 Fix rant/comment post/edit methods for rants/comments that contain non-alphanumerics in them
  Sources/SwiftRant/SwiftRant.swift
  Tests/SwiftRantTests/SwiftRantTests.swift
Labels: bug

#24 Hashable identifiable models
  Sources/SwiftRant/AvatarCustomization.swift
  Sources/SwiftRant/Comment.swift
  Sources/SwiftRant/NotificationFeed.swift
  Sources/SwiftRant/Profile.swift
  Sources/SwiftRant/Rant.swift
  Sources/SwiftRant/RantFeed.swift
  Sources/SwiftRant/RantInFeed.swift
  Sources/SwiftRant/RantInSubscribedFeed.swift
  Sources/SwiftRant/SubscribedFeed.swift
  Sources/SwiftRant/UserCredentials.swift
  Sources/SwiftRant/UsernameMap.swift
  Sources/SwiftRant/Weekly.swift
Labels: breaking change
